apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-app-1
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nutrition-app
  template:
    metadata: 
      labels:
        app: nutrition-app
    spec:
      containers:
      - name: nutrition-app
        image: icr.io/nutritionass_namespace/chandru1661/nutrition-app
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo Done Deploying sv-premier; sleep 3600;done"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
